language: node_js
node_js:
  - "10.16.0"
branches:
  only:
    - master
script:
  - echo "Deploying!"
install:
  - npm install
  - npm install -g @angular/cli
  - npm install -g firebase-tools
after_success:
  - ng lint
  - ng build --prod
  - firebase deploy --token $FIREBASE_TOKEN --only hosting
